
CREATE SEQUENCE public.pais_id_seq;
CREATE SEQUENCE public.estado_id_seq;
CREATE SEQUENCE public.municipio_id_seq;

CREATE TABLE pais
(
  id BIGINT GENERATED BY DEFAULT AS SEQUENCE pais_id_seq NOT NULL,
  nome longvarchar,
  primeiro boolean,
  CONSTRAINT pais_pkey PRIMARY KEY (id)
);

CREATE TABLE estado
(
  id BIGINT GENERATED BY DEFAULT AS SEQUENCE estado_id_seq NOT NULL,
  nome longvarchar,
  uf longvarchar,
  pais bigint,
  CONSTRAINT estado_pkey PRIMARY KEY (id),
  CONSTRAINT fk_estado_pais FOREIGN KEY (pais)
      REFERENCES pais (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE municipio
(
  id BIGINT GENERATED BY DEFAULT AS SEQUENCE municipio_id_seq NOT NULL,
  capital boolean,
  nome longvarchar,
  estado bigint,
  CONSTRAINT municipio_pkey PRIMARY KEY (id),
  CONSTRAINT fk_municipio_estado FOREIGN KEY (estado)
      REFERENCES estado (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);